#pragma once
// ============================================================
// UnixSocketChannel.hpp — v2.1.1
// Encrypted, authenticated Unix Domain Socket IPC channel.
//
// ── v2.1.1 Fixes (post-audit) ────────────────────────────────
//
//   [BUG-NET-01] CRITICAL — IpcChannelKey::derive() wrong class/method name:
//     Called `SecureKeyDerivation::hkdfDerive()` — neither the class name
//     nor the method name exist. The actual API is:
//       class KeyDerivation { deriveKey(span<byte_t>, string_view, size_t) }
//     Additionally, `std::as_bytes(span<const char>)` produces
//     `span<const std::byte>`, which does NOT match the `std::string_view`
//     `context` parameter of `deriveKey()`. Triple error: wrong class,
//     wrong method, wrong argument type — would not compile.
//     Fix: `KeyDerivation::deriveKey(masterKey, IPC_HKDF_DOMAIN, 32u)`
//
//   [BUG-NET-02] CRITICAL — verifyPeer() uses SO_PEERCRED/struct ucred (Linux-only):
//     `SO_PEERCRED` with `struct ucred` is a Linux-specific ABI.
//     macOS uses `LOCAL_PEERCRED` (level SOL_LOCAL) with `struct xucred`.
//     FreeBSD similarly uses `LOCAL_PEERCRED`. The header claimed POSIX
//     compliance but this call is not in POSIX.1-2017. Code would fail
//     to compile on Apple Clang / Darwin targets.
//     Fix: `#ifdef __linux__` / `#elif __APPLE__` / `#else` dispatch.
//     macOS path: `getsockopt(fd, SOL_LOCAL, LOCAL_PEERCRED, &xucred_val, &len)`
//
//   [BUG-NET-03] MEDIUM — run() stores running_=true AFTER stop() may have
//     set running_=false; run() overwrites it, then loops forever on a
//     shutdown (EINVAL) socket:
//       1. Thread A: stop() → running_=false, shutdown(listenFd_)
//       2. Thread B: run() → running_=true  ← overwrites!
//       3. Thread B: accept() → EINVAL (fd shut down)
//       4. errno != EINTR, != EAGAIN → logger_.error() → continue → ∞ loop
//     Fix: Add `while (running_.load(acquire))` pre-check BEFORE `accept()`.
//     The post-accept check (NET-02) is retained as belt-and-suspenders.
//
// ── v2.1.0 Fixes ─────────────────────────────────────────────
//
//   [NET-01] MEDIUM — writeFull() MSG_NOSIGNAL (Linux-only).
//     Fix: platform dispatch (#ifdef __APPLE__ → SO_NOSIGPIPE).
//
//   [NET-02] LOW — accept loop: one extra connection after stop().
//     Fix: check running_ immediately after every accept() return.
//
//   [NET-03] LOW — Channel key derivation not enforced by API.
//     Fix: IpcChannelKey::derive() helper with domain separation.
//
//   [NET-04] INFO — chmod(0600) window after bind().
//     Fix: umask(0177) before bind(), restore after.
//
// ── v2.0.1 Fixes ─────────────────────────────────────────────
//
//   [BUG-IPC-01] CRITICAL — encryptMessage() AAD mismatch → GCM always fails.
//   [BUG-IPC-02] CRITICAL — Result<UnixSocketServer/Client> won't compile.
//   [BUG-IPC-03] MEDIUM   — IpcMessage::serialise() returned {} on error.
//   [BUG-IPC-04] LOW      — recvMessage minimum payload check too loose.
//
// ── v2.0 Fixes (N01–N08) ─────────────────────────────────────
//
//   [N01] TOCTOU — unlink() before bind() (no exists() check).
//   [N02] Short read/write — readFull()/writeFull() loop.
//   [N03] DoS — validate payload size BEFORE allocating.
//   [N04] Peer auth — SO_PEERCRED verified BEFORE any data read.
//   [N05] SIGPIPE — SIG_IGN set in create()/connect().
//   [N06] Timeouts — applied immediately after accept()/connect().
//   [N07] RAII — socket file removed by UnixSocketServer destructor.
//   [N08] Portability — Windows Named Pipe stub with same API surface.
//
// Wire format (per message):
//   [4 bytes] MAGIC   = 0x53_46_57_4D ("SFWM")
//   [4 bytes] LENGTH  = uint32_t little-endian (byte count of PAYLOAD)
//   [n bytes] PAYLOAD = AES-256-GCM envelope
//
// AES-256-GCM envelope layout (generated by CryptoEngine):
//   [12 bytes] IV  (random per message, generated inside encryptAESGCM)
//   [16 bytes] GCM authentication tag
//   [ r bytes] ciphertext of serialised IpcMessage
//
// Channel key — ALWAYS derive via IpcChannelKey::derive(), never use
//               the raw master key directly:
//
//   auto keyRes = IpcChannelKey::derive(masterKey);  // HKDF domain-separated
//   auto srvRes = UnixSocketServer::create(path, keyRes.value, logger);
//
// Standards:
//   NIST SP 800-38D   (AES-GCM authenticated encryption)
//   NIST SP 800-108   (HKDF domain separation — IPC_HKDF_DOMAIN)
//   POSIX.1-2017      (Unix domain sockets, umask)
//   CERT MEM06-C      (locked buffers via SecBytes/SecureAllocator)
//   CWE-362           (N01/N04 TOCTOU / peer verification)
//   CWE-400           (N03 uncontrolled resource allocation)
// ============================================================

#include "SecureCore.hpp"
#include "CryptoEngine.hpp"
#include "InputValidator.hpp"
#include "MemoryGuard.hpp"
#include "SecureLogger.hpp"
#include "SecureKeyDerivation.hpp"   // [NET-03] KeyDerivation::deriveKey()

#include <cstdint>
#include <cstring>
#include <string>
#include <string_view>
#include <vector>
#include <functional>
#include <atomic>
#include <memory>

// ── Platform includes ─────────────────────────────────────────────────────────
#if defined(_WIN32) || defined(_WIN64)
#  define SECFW_IPC_WINDOWS 1
#  ifndef WIN32_LEAN_AND_MEAN
#    define WIN32_LEAN_AND_MEAN
#  endif
#  include <windows.h>
#else
#  define SECFW_IPC_UNIX 1
#  include <sys/socket.h>
#  include <sys/un.h>
#  include <sys/types.h>
#  include <sys/stat.h>
#  include <unistd.h>
#  include <cerrno>
#  include <cstring>
#  include <csignal>
#  include <fcntl.h>
// [BUG-NET-02 FIX]: macOS peer credential headers
#  ifdef __APPLE__
#    include <sys/socket.h>  // SOL_LOCAL, LOCAL_PEERCRED
#    include <sys/ucred.h>   // struct xucred
#  endif
#  ifdef __linux__
// struct ucred, SO_PEERCRED — defined via sys/socket.h already included
#  endif
#endif

namespace SecFW {

// ══════════════════════════════════════════════════════════════════════════════
// Constants
// ══════════════════════════════════════════════════════════════════════════════

// [N03] Hard cap. Reject BEFORE allocation — never alloc-then-check.
static constexpr std::size_t IPC_MAX_PAYLOAD_BYTES = 1u * 1024u * 1024u; // 1 MiB

// Frame header: 4-byte magic + 4-byte length = 8 bytes total
static constexpr uint8_t     IPC_MAGIC[4]    = { 0x53, 0x46, 0x57, 0x4D }; // "SFWM"
static constexpr std::size_t IPC_HEADER_SIZE = 8;

// AES-GCM envelope overhead: IV(12) + TAG(16) = 28 bytes
// CryptoEngine::encryptAESGCM output layout: [IV(12)] [TAG(16)] [CIPHERTEXT(N)]
static constexpr std::size_t IPC_GCM_IV_LEN   = 12;
static constexpr std::size_t IPC_GCM_TAG_LEN  = 16;
static constexpr std::size_t IPC_GCM_OVERHEAD = IPC_GCM_IV_LEN + IPC_GCM_TAG_LEN; // 28

// [BUG-IPC-04 FIX]: Minimum valid payload = GCM overhead + 4-byte body-len prefix.
static constexpr std::size_t IPC_MIN_PAYLOAD_BYTES = IPC_GCM_OVERHEAD + 4; // 32

// [N06] Per-connection recv/send timeouts
static constexpr int IPC_RECV_TIMEOUT_SEC = 5;
static constexpr int IPC_SEND_TIMEOUT_SEC = 5;

static constexpr int IPC_LISTEN_BACKLOG = 16;

// HKDF info/context label for channel key derivation.
// MUST be passed to IpcChannelKey::derive() — never use master key directly.
static constexpr std::string_view IPC_HKDF_DOMAIN = "secfw-ipc-channel-v1";

// ══════════════════════════════════════════════════════════════════════════════
// [NET-03] IpcChannelKey — enforced HKDF derivation helper
// ══════════════════════════════════════════════════════════════════════════════
//
// ALWAYS use this to produce the channelKey parameter for create()/connect().
// Passing the raw master key violates NIST SP 800-108 domain separation.
//
// Usage:
//   auto keyRes = IpcChannelKey::derive(masterKey);
//   if (keyRes.fail()) { /* handle */ }
//   auto srvRes = UnixSocketServer::create(path, keyRes.value, logger);
//
struct IpcChannelKey {
    [[nodiscard]] static Result<SecBytes> derive(const SecBytes& masterKey)
    {
        // [BUG-NET-01 FIX]: Correct class is `KeyDerivation` (not SecureKeyDerivation),
        // correct method is `deriveKey(span<byte_t>, string_view, size_t)`.
        // IPC_HKDF_DOMAIN is std::string_view — pass directly as context, no span conversion.
        return KeyDerivation::deriveKey(
            std::span<const byte_t>(masterKey.data(), masterKey.size()),
            IPC_HKDF_DOMAIN,
            32u);
    }
};

// ══════════════════════════════════════════════════════════════════════════════
// IpcPeerInfo — verified peer credentials from SO_PEERCRED / LOCAL_PEERCRED
// ══════════════════════════════════════════════════════════════════════════════

struct IpcPeerInfo {
    uid_t uid      { 0 };
    gid_t gid      { 0 };
    pid_t pid      { 0 };  // Note: not available on macOS via xucred; set to 0.
    bool  verified { false };
};

// ══════════════════════════════════════════════════════════════════════════════
// IpcMessage — application-level message
// ══════════════════════════════════════════════════════════════════════════════
//
// Body is opaque bytes (JSON recommended).
//
// Serialised on-wire inside GCM ciphertext:
//   [4 bytes] body_len  — uint32_t little-endian
//   [n bytes] body      — UTF-8 string

struct IpcMessage {
    std::string body;

    static constexpr std::size_t MAX_BODY_BYTES =
        IPC_MAX_PAYLOAD_BYTES - IPC_GCM_OVERHEAD - 4;

    // [BUG-IPC-03 FIX]: Returns Result<SecBytes> so callers use .fail() cleanly.
    [[nodiscard]] Result<SecBytes> serialise() const {
        if (body.size() > MAX_BODY_BYTES)
            return Result<SecBytes>::Failure(SecurityStatus::ERR_INPUT_INVALID,
                "IpcMessage::serialise: body " + std::to_string(body.size()) +
                " bytes > MAX_BODY_BYTES " + std::to_string(MAX_BODY_BYTES));

        auto bodyLen = static_cast<uint32_t>(body.size());
        SecBytes out;
        out.reserve(4 + body.size());
        out.push_back(static_cast<byte_t>( bodyLen        & 0xFF));
        out.push_back(static_cast<byte_t>((bodyLen >>  8) & 0xFF));
        out.push_back(static_cast<byte_t>((bodyLen >> 16) & 0xFF));
        out.push_back(static_cast<byte_t>((bodyLen >> 24) & 0xFF));
        for (char c : body) out.push_back(static_cast<byte_t>(c));
        return Result<SecBytes>::Success(std::move(out));
    }

    [[nodiscard]] static Result<IpcMessage> deserialise(const SecBytes& raw) {
        if (raw.size() < 4)
            return Result<IpcMessage>::Failure(SecurityStatus::ERR_INPUT_INVALID,
                "IpcMessage::deserialise: too short for body-length prefix");

        uint32_t bodyLen =
              static_cast<uint32_t>(raw[0])
            | static_cast<uint32_t>(raw[1]) <<  8
            | static_cast<uint32_t>(raw[2]) << 16
            | static_cast<uint32_t>(raw[3]) << 24;

        if (bodyLen > MAX_BODY_BYTES)
            return Result<IpcMessage>::Failure(SecurityStatus::ERR_INPUT_INVALID,
                "IpcMessage::deserialise: body_len " + std::to_string(bodyLen) +
                " > MAX_BODY_BYTES " + std::to_string(MAX_BODY_BYTES));

        if (raw.size() < 4 + static_cast<std::size_t>(bodyLen))
            return Result<IpcMessage>::Failure(SecurityStatus::ERR_INPUT_INVALID,
                "IpcMessage::deserialise: truncated body (have " +
                std::to_string(raw.size() - 4) +
                ", need " + std::to_string(bodyLen) + ")");

        IpcMessage msg;
        msg.body.assign(reinterpret_cast<const char*>(raw.data() + 4), bodyLen);
        return Result<IpcMessage>::Success(std::move(msg));
    }
};

// ══════════════════════════════════════════════════════════════════════════════
// Internal platform helpers (namespace detail)
// ══════════════════════════════════════════════════════════════════════════════

namespace detail {

#ifdef SECFW_IPC_UNIX

using SocketFd = int;
static constexpr SocketFd INVALID_FD = -1;

// ── [NET-01 FIX] setSoPeerNosigpipe ──────────────────────────────────────────
// On macOS, MSG_NOSIGNAL is not available. Instead we set SO_NOSIGPIPE once on
// each new socket fd. On Linux/FreeBSD this is a no-op (MSG_NOSIGNAL is used
// per-call in writeFull instead, which is the preferred approach on Linux).

inline void setSoPeerNosigpipe([[maybe_unused]] SocketFd fd) noexcept
{
#ifdef __APPLE__
    int opt = 1;
    ::setsockopt(fd, SOL_SOCKET, SO_NOSIGPIPE, &opt, sizeof(opt));
    // Ignoring return: SIG_IGN is our fallback if this fails.
#endif
    // On Linux/FreeBSD: no-op; MSG_NOSIGNAL is used per send() call.
}

// ── [N02 FIX] readFull ───────────────────────────────────────────────────────
// Loops until all `len` bytes received. Short reads are normal on stream sockets.

[[nodiscard]] inline Result<void> readFull(SocketFd fd, void* buf, std::size_t len)
{
    byte_t*     ptr       = static_cast<byte_t*>(buf);
    std::size_t remaining = len;
    while (remaining > 0) {
        ssize_t n = ::recv(fd, ptr, remaining, MSG_WAITALL);
        if (n == 0)
            return Result<void>::Failure(SecurityStatus::ERR_CONN_CLOSED,
                "EOF after " + std::to_string(len - remaining) +
                "/" + std::to_string(len) + " bytes");
        if (n < 0) {
            int e = errno;
            if (e == EINTR)  continue;
            if (e == EAGAIN || e == EWOULDBLOCK)
                return Result<void>::Failure(SecurityStatus::ERR_TIMEOUT,
                    "recv timed out (SO_RCVTIMEO = " +
                    std::to_string(IPC_RECV_TIMEOUT_SEC) + "s)");
            return Result<void>::Failure(SecurityStatus::ERR_NETWORK_FAIL,
                std::string("recv: ") + ::strerror(e));
        }
        ptr       += static_cast<std::size_t>(n);
        remaining -= static_cast<std::size_t>(n);
    }
    return Result<void>::Success();
}

// ── [N02 FIX, N05 FIX, NET-01 FIX] writeFull ────────────────────────────────
// Loops until all `len` bytes sent.
//
// SIGPIPE suppression strategy:
//   Linux / FreeBSD : MSG_NOSIGNAL flag on every send() call (preferred).
//   macOS           : SO_NOSIGPIPE set once on the fd (via setSoPeerNosigpipe),
//                     send() uses flag 0.
// Global SIGPIPE→SIG_IGN is set in create()/connect() as belt-and-suspenders.

[[nodiscard]] inline Result<void> writeFull(SocketFd    fd,
                                             const void* buf, std::size_t len)
{
#ifdef __APPLE__
    static constexpr int SEND_FLAGS = 0;         // SO_NOSIGPIPE set per-fd
#else
    static constexpr int SEND_FLAGS = MSG_NOSIGNAL;  // Linux / FreeBSD per-call
#endif

    const byte_t* ptr       = static_cast<const byte_t*>(buf);
    std::size_t   remaining = len;
    while (remaining > 0) {
        ssize_t n = ::send(fd, ptr, remaining, SEND_FLAGS);
        if (n < 0) {
            int e = errno;
            if (e == EINTR) continue;
            if (e == EPIPE || e == ECONNRESET)
                return Result<void>::Failure(SecurityStatus::ERR_CONN_CLOSED,
                    "peer closed during send (EPIPE/ECONNRESET)");
            if (e == EAGAIN || e == EWOULDBLOCK)
                return Result<void>::Failure(SecurityStatus::ERR_TIMEOUT,
                    "send timed out (SO_SNDTIMEO = " +
                    std::to_string(IPC_SEND_TIMEOUT_SEC) + "s)");
            return Result<void>::Failure(SecurityStatus::ERR_NETWORK_FAIL,
                std::string("send: ") + ::strerror(e));
        }
        ptr       += static_cast<std::size_t>(n);
        remaining -= static_cast<std::size_t>(n);
    }
    return Result<void>::Success();
}

// ── [N06 FIX] applyTimeouts ──────────────────────────────────────────────────
// Must be called on every accepted/connected socket BEFORE reading any data.

[[nodiscard]] inline Result<void> applyTimeouts(SocketFd fd)
{
    struct timeval tv{ IPC_RECV_TIMEOUT_SEC, 0 };
    if (::setsockopt(fd, SOL_SOCKET, SO_RCVTIMEO, &tv, sizeof(tv)) != 0)
        return Result<void>::Failure(SecurityStatus::ERR_NETWORK_FAIL,
            std::string("SO_RCVTIMEO: ") + ::strerror(errno));
    tv.tv_sec = IPC_SEND_TIMEOUT_SEC;
    if (::setsockopt(fd, SOL_SOCKET, SO_SNDTIMEO, &tv, sizeof(tv)) != 0)
        return Result<void>::Failure(SecurityStatus::ERR_NETWORK_FAIL,
            std::string("SO_SNDTIMEO: ") + ::strerror(errno));
    return Result<void>::Success();
}

// ── [N04 FIX, BUG-NET-02 FIX] verifyPeer ────────────────────────────────────
// Reads peer credentials BEFORE any data is read. Returns peer UID/GID/PID.
//
// Platform dispatch:
//   Linux   : SO_PEERCRED + struct ucred  (uid, gid, pid all available)
//   macOS   : LOCAL_PEERCRED + struct xucred via SOL_LOCAL  (uid, gid; pid = 0)
//   Other   : returns ERR_PEER_REJECTED (unsupported platform)
//
// Note: SO_PEERCRED/LOCAL_PEERCRED are NOT in POSIX.1-2017; they are
// platform-specific extensions that provide equivalent functionality.

[[nodiscard]] inline Result<IpcPeerInfo> verifyPeer(SocketFd fd)
{
#if defined(__linux__)
    struct ucred cred{};
    socklen_t    len = sizeof(cred);
    if (::getsockopt(fd, SOL_SOCKET, SO_PEERCRED, &cred, &len) != 0)
        return Result<IpcPeerInfo>::Failure(SecurityStatus::ERR_PEER_REJECTED,
            std::string("SO_PEERCRED: ") + ::strerror(errno));
    return Result<IpcPeerInfo>::Success(
        IpcPeerInfo{ cred.uid, cred.gid, cred.pid, true });

#elif defined(__APPLE__) || defined(__FreeBSD__) || defined(__OpenBSD__)
    // [BUG-NET-02 FIX]: macOS / BSD use LOCAL_PEERCRED + struct xucred.
    // xucred has cr_uid and cr_groups but NOT cr_pid.
    struct xucred cred{};
    socklen_t     len = sizeof(cred);
    if (::getsockopt(fd, SOL_LOCAL, LOCAL_PEERCRED, &cred, &len) != 0)
        return Result<IpcPeerInfo>::Failure(SecurityStatus::ERR_PEER_REJECTED,
            std::string("LOCAL_PEERCRED: ") + ::strerror(errno));
    return Result<IpcPeerInfo>::Success(
        IpcPeerInfo{ cred.cr_uid,
                     (cred.cr_ngroups > 0 ? cred.cr_groups[0] : static_cast<gid_t>(0)),
                     0,   // pid not available via xucred
                     true });

#else
    (void)fd;
    // Unsupported platform: fail closed (deny by default).
    return Result<IpcPeerInfo>::Failure(SecurityStatus::ERR_PEER_REJECTED,
        "verifyPeer: peer credential check not supported on this platform");
#endif
}

// ── [N01 FIX, N07 FIX] cleanupSocketFile ────────────────────────────────────
// Unconditional unlink — ENOENT is expected and silently ignored.
// Never call exists() before unlinking (TOCTOU).

inline void cleanupSocketFile(const std::string& path) noexcept {
    ::unlink(path.c_str());
}

// ── [BUG-IPC-01 FIX] encryptMessage ─────────────────────────────────────────
// CryptoEngine generates its own IV internally.
// Output layout: [IV(12)] [TAG(16)] [CIPHERTEXT(N)].

[[nodiscard]] inline Result<SecBytes> encryptMessage(
    const SecBytes& plaintext, const SecBytes& channelKey)
{
    auto r = CryptoEngine::encryptAESGCM(plaintext, channelKey);
    if (r.fail())
        return Result<SecBytes>::Failure(r.status, "encryptMessage: " + r.message);
    return Result<SecBytes>::Success(std::move(r.value));
}

// ── decryptMessage ────────────────────────────────────────────────────────────
// Reads IV from [0..11], TAG from [12..27], decrypts [28..N].

[[nodiscard]] inline Result<SecBytes> decryptMessage(
    const SecBytes& envelope, const SecBytes& channelKey)
{
    if (envelope.size() < IPC_GCM_OVERHEAD)
        return Result<SecBytes>::Failure(SecurityStatus::ERR_CRYPTO_FAIL,
            "decryptMessage: envelope " + std::to_string(envelope.size()) +
            " < GCM overhead " + std::to_string(IPC_GCM_OVERHEAD));
    auto r = CryptoEngine::decryptAESGCM(envelope, channelKey);
    if (r.fail())
        return Result<SecBytes>::Failure(r.status, "decryptMessage: " + r.message);
    return Result<SecBytes>::Success(std::move(r.value));
}

#endif // SECFW_IPC_UNIX

} // namespace detail

// ══════════════════════════════════════════════════════════════════════════════
// Public framing API
// ══════════════════════════════════════════════════════════════════════════════

#ifdef SECFW_IPC_UNIX

[[nodiscard]] inline Result<void> sendMessage(detail::SocketFd  fd,
                                               const IpcMessage& msg,
                                               const SecBytes&   channelKey)
{
    auto ser = msg.serialise();
    if (ser.fail()) return Result<void>::Failure(ser.status, ser.message);

    auto enc = detail::encryptMessage(ser.value, channelKey);
    if (enc.fail()) return Result<void>::Failure(enc.status, enc.message);

    const auto payloadLen = static_cast<uint32_t>(enc.value.size());
    uint8_t header[IPC_HEADER_SIZE];
    std::memcpy(header, IPC_MAGIC, 4);
    header[4] = static_cast<uint8_t>( payloadLen        & 0xFF);
    header[5] = static_cast<uint8_t>((payloadLen >>  8) & 0xFF);
    header[6] = static_cast<uint8_t>((payloadLen >> 16) & 0xFF);
    header[7] = static_cast<uint8_t>((payloadLen >> 24) & 0xFF);

    auto hw = detail::writeFull(fd, header, IPC_HEADER_SIZE);
    if (hw.fail()) return hw;
    return detail::writeFull(fd, enc.value.data(), enc.value.size());
}

[[nodiscard]] inline Result<IpcMessage> recvMessage(detail::SocketFd fd,
                                                     const SecBytes&  channelKey)
{
    uint8_t header[IPC_HEADER_SIZE];
    {
        auto r = detail::readFull(fd, header, IPC_HEADER_SIZE);
        if (r.fail()) return Result<IpcMessage>::Failure(r.status, r.message);
    }

    if (std::memcmp(header, IPC_MAGIC, 4) != 0)
        return Result<IpcMessage>::Failure(SecurityStatus::ERR_INPUT_INVALID,
            "recvMessage: invalid frame magic");

    uint32_t payloadLen =
          static_cast<uint32_t>(header[4])
        | static_cast<uint32_t>(header[5]) <<  8
        | static_cast<uint32_t>(header[6]) << 16
        | static_cast<uint32_t>(header[7]) << 24;

    if (payloadLen > IPC_MAX_PAYLOAD_BYTES)
        return Result<IpcMessage>::Failure(SecurityStatus::ERR_INPUT_INVALID,
            "recvMessage: payload_len=" + std::to_string(payloadLen) +
            " > IPC_MAX_PAYLOAD_BYTES — possible DoS frame");

    if (payloadLen < IPC_MIN_PAYLOAD_BYTES)
        return Result<IpcMessage>::Failure(SecurityStatus::ERR_INPUT_INVALID,
            "recvMessage: payload_len=" + std::to_string(payloadLen) +
            " < IPC_MIN_PAYLOAD_BYTES=" + std::to_string(IPC_MIN_PAYLOAD_BYTES));

    SecBytes payload(payloadLen);
    {
        auto r = detail::readFull(fd, payload.data(), payloadLen);
        if (r.fail()) return Result<IpcMessage>::Failure(r.status, r.message);
    }

    auto decRes = detail::decryptMessage(payload, channelKey);
    if (decRes.fail())
        return Result<IpcMessage>::Failure(decRes.status, decRes.message);

    return IpcMessage::deserialise(decRes.value);
}

// ══════════════════════════════════════════════════════════════════════════════
// UnixSocketServer
// ══════════════════════════════════════════════════════════════════════════════

class UnixSocketServer final {
public:
    using ConnectionHandler = std::function<void(
        detail::SocketFd   fd,
        const IpcPeerInfo& peer,
        const SecBytes&    channelKey,
        SecureLogger&      logger)>;

    // ── create ────────────────────────────────────────────────────────────────
    // [BUG-IPC-02 FIX]: Returns unique_ptr — UnixSocketServer is not
    // default-constructible (owns listenFd_).
    //
    // channelKey MUST be derived via IpcChannelKey::derive(masterKey).
    // Passing the raw master key violates NIST SP 800-108.
    //
    // [NET-04 FIX]: umask(0177) set before bind() so the socket file is
    // created with mode 0600. Restored after chmod() call.
    //
    // allowedUid: UID allowed to connect. Defaults to calling process eUID.
    // Pass 0 to restrict to root only.

    [[nodiscard]] static Result<std::unique_ptr<UnixSocketServer>> create(
        const std::string& socketPath,
        SecBytes           channelKey,
        SecureLogger&      logger,
        uid_t              allowedUid = static_cast<uid_t>(-1))
    {
        // [BUG-E04]: isValidSocketPath() enforces UNIX_PATH_MAX (108 bytes)
        auto pathCheck = InputValidator::isValidSocketPath(socketPath);
        if (pathCheck.fail())
            return Result<std::unique_ptr<UnixSocketServer>>::Failure(
                pathCheck.status, "UnixSocketServer::create: " + pathCheck.message);

        ::signal(SIGPIPE, SIG_IGN);                      // [N05 FIX] belt-and-suspenders
        detail::cleanupSocketFile(socketPath);            // [N01 FIX] no TOCTOU

        int fd = ::socket(AF_UNIX, SOCK_STREAM, 0);
        if (fd < 0)
            return Result<std::unique_ptr<UnixSocketServer>>::Failure(
                SecurityStatus::ERR_NETWORK_FAIL,
                std::string("socket: ") + ::strerror(errno));

        struct sockaddr_un addr{};
        addr.sun_family = AF_UNIX;
        std::strncpy(addr.sun_path, socketPath.c_str(), sizeof(addr.sun_path) - 1);

        // [NET-04 FIX]: Restrict umask so bind() creates socket with mode 0600.
        // Note: umask() is process-wide. On Linux >= 4.7 it is per-thread,
        // but on older kernels concurrent create() calls from different threads
        // may interfere. Single-threaded startup is the safe pattern.
        mode_t oldUmask = ::umask(0177); // 0777 & ~0177 = 0600

        if (::bind(fd, reinterpret_cast<sockaddr*>(&addr), sizeof(addr)) != 0) {
            int e = errno;
            ::umask(oldUmask);
            ::close(fd);
            return Result<std::unique_ptr<UnixSocketServer>>::Failure(
                SecurityStatus::ERR_NETWORK_FAIL,
                std::string("bind: ") + ::strerror(e));
        }

        // Restore umask before any further file operations
        ::umask(oldUmask);

        // Belt-and-suspenders: explicit chmod in case the kernel did not apply
        // our umask to the socket file (kernel behaviour varies for AF_UNIX).
        if (::chmod(socketPath.c_str(), 0600) != 0) {
            int e = errno;
            ::close(fd);
            detail::cleanupSocketFile(socketPath);
            return Result<std::unique_ptr<UnixSocketServer>>::Failure(
                SecurityStatus::ERR_NETWORK_FAIL,
                std::string("chmod(0600) socket: ") + ::strerror(e));
        }

        if (::listen(fd, IPC_LISTEN_BACKLOG) != 0) {
            int e = errno;
            ::close(fd);
            detail::cleanupSocketFile(socketPath);
            return Result<std::unique_ptr<UnixSocketServer>>::Failure(
                SecurityStatus::ERR_NETWORK_FAIL,
                std::string("listen: ") + ::strerror(e));
        }

        uid_t effectiveUid = (allowedUid == static_cast<uid_t>(-1))
            ? ::getuid() : allowedUid;

        // Local helper subclass so make_unique can reach protected ctor.
        // struct Priv has a public constructor (struct default) that forwards
        // to the protected UnixSocketServer constructor.
        struct Priv : UnixSocketServer {
            Priv(int f, std::string p, SecBytes k, SecureLogger& l, uid_t u)
                : UnixSocketServer(f, std::move(p), std::move(k), l, u) {}
        };
        auto ptr = std::make_unique<Priv>(
            fd, socketPath, std::move(channelKey), logger, effectiveUid);

        return Result<std::unique_ptr<UnixSocketServer>>::Success(std::move(ptr));
    }

    // ── run — blocking accept loop ────────────────────────────────────────────
    // [N04 FIX]: SO_PEERCRED / LOCAL_PEERCRED verified on every socket before data.
    // [N06 FIX]: Timeouts and SO_NOSIGPIPE applied immediately after accept().
    // [NET-01 FIX]: setSoPeerNosigpipe() called on accepted fd.
    // [NET-02 FIX]: running_ checked immediately after accept() returns,
    //   before processing — if stop() raced with accept(), fd is discarded.
    // [BUG-NET-03 FIX]: running_ pre-checked at top of while() loop so that
    //   if stop() fires BEFORE run() enters the loop, run() never enters it.
    //   Without this, run() would overwrite running_=false with running_=true,
    //   then accept() on the shutdown fd → EINVAL storm.

    void run(ConnectionHandler handler) {
        running_.store(true, std::memory_order_relaxed);
        logger_.info("UnixSocketServer: listening on " + socketPath_);

        // [BUG-NET-03 FIX]: Pre-check running_ BEFORE blocking in accept().
        // This closes the race where stop() fires before run() enters the loop.
        while (running_.load(std::memory_order_acquire)) {
            int clientFd = ::accept(listenFd_, nullptr, nullptr);

            // [NET-02 FIX]: Post-check — even if a valid fd was returned by
            // accept(), discard it if stop() was called while accept() blocked.
            if (!running_.load(std::memory_order_acquire)) {
                if (clientFd >= 0) ::close(clientFd); // discard post-stop connection
                break;
            }

            if (clientFd < 0) {
                int e = errno;
                if (e == EINTR) continue;               // signal — re-check running_
                if (e == EINVAL) {                      // fd was shutdown'd by stop()
                    // Should not reach here if running_ pre-check works,
                    // but handle it gracefully as belt-and-suspenders.
                    break;
                }
                logger_.error("accept: " + std::string(::strerror(e)));
                continue;
            }

            // [NET-01 FIX]: Set SO_NOSIGPIPE on macOS; no-op on Linux.
            detail::setSoPeerNosigpipe(clientFd);

            // [N06 FIX]: Timeouts before reading anything
            auto toRes = detail::applyTimeouts(clientFd);
            if (toRes.fail()) {
                logger_.warn("applyTimeouts: " + toRes.message);
                ::close(clientFd); continue;
            }

            // [N04 FIX]: Peer credentials before data
            auto peerRes = detail::verifyPeer(clientFd);
            if (peerRes.fail()) {
                logger_.warn("peer credential check: " + peerRes.message);
                ::close(clientFd); continue;
            }

            const IpcPeerInfo& peer = peerRes.value;
            if (peer.uid != allowedUid_) {
                logger_.warn("rejected UID=" + std::to_string(peer.uid) +
                             " PID=" + std::to_string(peer.pid) +
                             " (allowed=" + std::to_string(allowedUid_) + ")");
                ::close(clientFd); continue;
            }

            logger_.info("accepted PID=" + std::to_string(peer.pid) +
                         " UID=" + std::to_string(peer.uid));

            try { handler(clientFd, peer, channelKey_, logger_); }
            catch (const std::exception& e) {
                logger_.error("handler exception: " + std::string(e.what()));
            } catch (...) {
                logger_.error("handler threw unknown exception");
            }

            ::close(clientFd);
        }

        logger_.info("UnixSocketServer: accept loop exited");
    }

    // stop() is safe to call from another thread or signal handler.
    // shutdown() unblocks accept(); running_=false causes the loop to exit.
    void stop() noexcept {
        running_.store(false, std::memory_order_release);
        if (listenFd_ >= 0) ::shutdown(listenFd_, SHUT_RDWR);
    }

    // [N07 FIX]: RAII — socket file removed on destructor
    ~UnixSocketServer() noexcept {
        stop();
        if (listenFd_ >= 0) { ::close(listenFd_); listenFd_ = -1; }
        if (!socketPath_.empty()) detail::cleanupSocketFile(socketPath_);
    }

    UnixSocketServer(const UnixSocketServer&)            = delete;
    UnixSocketServer& operator=(const UnixSocketServer&) = delete;
    UnixSocketServer(UnixSocketServer&&)                 = delete;
    UnixSocketServer& operator=(UnixSocketServer&&)      = delete;

protected:
    UnixSocketServer(int fd, std::string path,
                     SecBytes key, SecureLogger& log, uid_t uid)
        : listenFd_(fd), socketPath_(std::move(path))
        , channelKey_(std::move(key)), logger_(log)
        , allowedUid_(uid), running_(false) {}

private:
    int               listenFd_   { -1 };
    std::string       socketPath_ {};
    SecBytes          channelKey_ {};
    SecureLogger&     logger_;
    uid_t             allowedUid_ { 0 };
    std::atomic<bool> running_    { false };
};

// ══════════════════════════════════════════════════════════════════════════════
// UnixSocketClient
// ══════════════════════════════════════════════════════════════════════════════

class UnixSocketClient final {
public:
    // [BUG-IPC-02 FIX]: Returns unique_ptr.
    // channelKey MUST be derived via IpcChannelKey::derive(masterKey).
    // [NET-01 FIX]: setSoPeerNosigpipe() applied immediately after connect().

    [[nodiscard]] static Result<std::unique_ptr<UnixSocketClient>> connect(
        const std::string& socketPath,
        SecBytes           channelKey)
    {
        auto pathCheck = InputValidator::isValidSocketPath(socketPath);
        if (pathCheck.fail())
            return Result<std::unique_ptr<UnixSocketClient>>::Failure(
                pathCheck.status,
                "UnixSocketClient::connect: " + pathCheck.message);

        ::signal(SIGPIPE, SIG_IGN);  // [N05 FIX]

        int fd = ::socket(AF_UNIX, SOCK_STREAM, 0);
        if (fd < 0)
            return Result<std::unique_ptr<UnixSocketClient>>::Failure(
                SecurityStatus::ERR_NETWORK_FAIL,
                std::string("socket: ") + ::strerror(errno));

        struct sockaddr_un addr{};
        addr.sun_family = AF_UNIX;
        std::strncpy(addr.sun_path, socketPath.c_str(), sizeof(addr.sun_path) - 1);

        if (::connect(fd, reinterpret_cast<sockaddr*>(&addr), sizeof(addr)) != 0) {
            int e = errno;
            ::close(fd);
            return Result<std::unique_ptr<UnixSocketClient>>::Failure(
                SecurityStatus::ERR_NETWORK_FAIL,
                std::string("connect: ") + ::strerror(e));
        }

        // [NET-01 FIX]: macOS SO_NOSIGPIPE
        detail::setSoPeerNosigpipe(fd);

        // [N06 FIX]: Timeouts on connected socket
        auto toRes = detail::applyTimeouts(fd);
        if (toRes.fail()) {
            ::close(fd);
            return Result<std::unique_ptr<UnixSocketClient>>::Failure(
                toRes.status, "UnixSocketClient: " + toRes.message);
        }

        struct Priv : UnixSocketClient {
            Priv(int f, SecBytes k) : UnixSocketClient(f, std::move(k)) {}
        };
        return Result<std::unique_ptr<UnixSocketClient>>::Success(
            std::make_unique<Priv>(fd, std::move(channelKey)));
    }

    [[nodiscard]] Result<void> send(const IpcMessage& msg) {
        return sendMessage(fd_, msg, channelKey_);
    }

    [[nodiscard]] Result<IpcMessage> recv() {
        return recvMessage(fd_, channelKey_);
    }

    ~UnixSocketClient() noexcept {
        if (fd_ >= 0) { ::close(fd_); fd_ = -1; }
    }

    UnixSocketClient(const UnixSocketClient&)            = delete;
    UnixSocketClient& operator=(const UnixSocketClient&) = delete;
    UnixSocketClient(UnixSocketClient&&)                 = delete;
    UnixSocketClient& operator=(UnixSocketClient&&)      = delete;

protected:
    UnixSocketClient(int fd, SecBytes key)
        : fd_(fd), channelKey_(std::move(key)) {}

private:
    int      fd_         { -1 };
    SecBytes channelKey_ {};
};

#endif // SECFW_IPC_UNIX

// ══════════════════════════════════════════════════════════════════════════════
// Windows Named Pipe stub — [N08] same API surface, not implemented
// ══════════════════════════════════════════════════════════════════════════════

#ifdef SECFW_IPC_WINDOWS

namespace detail { using SocketFd = HANDLE; }

struct IpcPeerInfo { uid_t uid{0}; gid_t gid{0}; pid_t pid{0}; bool verified{false}; };

class UnixSocketServer final {
public:
    using ConnectionHandler = std::function<void(detail::SocketFd,const IpcPeerInfo&,
                                                 const SecBytes&,SecureLogger&)>;
    static Result<std::unique_ptr<UnixSocketServer>> create(
        const std::string&, SecBytes, SecureLogger&, uid_t = 0) {
        return Result<std::unique_ptr<UnixSocketServer>>::Failure(
            SecurityStatus::ERR_INTERNAL, "not implemented on Windows");
    }
    void run(ConnectionHandler) {}
    void stop() noexcept {}
    ~UnixSocketServer() noexcept = default;
    UnixSocketServer(const UnixSocketServer&) = delete;
    UnixSocketServer& operator=(const UnixSocketServer&) = delete;
protected:
    UnixSocketServer() = default;
};

class UnixSocketClient final {
public:
    static Result<std::unique_ptr<UnixSocketClient>> connect(
        const std::string&, SecBytes) {
        return Result<std::unique_ptr<UnixSocketClient>>::Failure(
            SecurityStatus::ERR_INTERNAL, "not implemented on Windows");
    }
    [[nodiscard]] Result<void>       send(const IpcMessage&) {
        return Result<void>::Failure(SecurityStatus::ERR_INTERNAL, "not implemented");
    }
    [[nodiscard]] Result<IpcMessage> recv() {
        return Result<IpcMessage>::Failure(SecurityStatus::ERR_INTERNAL, "not implemented");
    }
    ~UnixSocketClient() noexcept = default;
    UnixSocketClient(const UnixSocketClient&) = delete;
    UnixSocketClient& operator=(const UnixSocketClient&) = delete;
protected:
    UnixSocketClient() = default;
};

#endif // SECFW_IPC_WINDOWS

} // namespace SecFW
