#pragma once
// ============================================================
// UnixSocketChannel.hpp — v2.0.1
// Encrypted, authenticated Unix Domain Socket IPC channel.
//
// Bug fixes in v2.0.1 (post-audit):
//
//   [BUG-IPC-01] CRITICAL — encryptMessage() AAD mismatch:
//     v2.0 generated a random ivRes and passed it as the 3rd
//     argument to CryptoEngine::encryptAESGCM(). The 3rd param
//     is `aad` (Additional Authenticated Data), NOT an IV.
//     CryptoEngine generates its own IV internally.
//     Since decryptAESGCM() was called with no aad, the GCM
//     authentication tag failed on EVERY message.
//     Fix: Remove the spurious ivRes. Call encryptAESGCM with
//     no aad. CryptoEngine prepends the IV to the output blob.
//
//   [BUG-IPC-02] CRITICAL — Result<UnixSocketServer/Client> won't compile:
//     Result<T> stores `T value {}`, which zero-initialises T.
//     UnixSocketServer/Client have no default constructor (they
//     own OS file descriptors). Attempting to instantiate
//     Result<UnixSocketServer> fails at compile time.
//     Fix: factory methods return
//     Result<std::unique_ptr<UnixSocketServer/Client>>.
//
//   [BUG-IPC-03] MEDIUM — IpcMessage::serialise() returns {} on error:
//     Callers had to infer error via a dual-variable check
//     (`empty() && !body.empty()`). If body was empty the
//     check was silently skipped.
//     Fix: serialise() now returns Result<SecBytes>.
//
//   [BUG-IPC-04] LOW — recvMessage minimum payload check too loose:
//     Checked payloadLen < IPC_GCM_OVERHEAD (28). But valid
//     payloads also need 4 bytes for the body-length prefix
//     inside the plaintext. Values 28-31 passed the check but
//     failed in deserialise(). Rejection now happens earlier.
//     Fix: IPC_MIN_PAYLOAD_BYTES = IPC_GCM_OVERHEAD + 4 = 32.
//
// Original N01-N08 fixes from v2.0 are unchanged.
//
// Wire format (per message):
//   [4 bytes] MAGIC   = 0x53_46_57_4D ("SFWM")
//   [4 bytes] LENGTH  = uint32_t little-endian (byte count of PAYLOAD)
//   [n bytes] PAYLOAD = AES-256-GCM envelope
//
// AES-256-GCM envelope layout (generated by CryptoEngine):
//   [12 bytes] IV (random per message, generated inside encryptAESGCM)
//   [16 bytes] GCM authentication tag
//   [r  bytes] ciphertext of serialised IpcMessage body
//
// Channel key: derive via SecureKeyDerivation::derive(master, 32, IPC_HKDF_DOMAIN)
//
// Standards:
//   NIST SP 800-38D   (AES-GCM)
//   NIST SP 800-108   (HKDF domain separation)
//   POSIX.1-2017      (Unix domain sockets, SO_PEERCRED)
//   CERT MEM06-C      (locked buffers)
//   CWE-362           (N01, N04 TOCTOU / peer verification)
//   CWE-400           (N03 uncontrolled resource allocation)
// ============================================================

#include "SecureCore.hpp"
#include "CryptoEngine.hpp"
#include "InputValidator.hpp"
#include "MemoryGuard.hpp"
#include "SecureLogger.hpp"

#include <cstdint>
#include <cstring>
#include <string>
#include <string_view>
#include <vector>
#include <functional>
#include <atomic>
#include <memory>

// ── Platform includes ─────────────────────────────────────────────────────────
#if defined(_WIN32) || defined(_WIN64)
#  define SECFW_IPC_WINDOWS 1
#  ifndef WIN32_LEAN_AND_MEAN
#    define WIN32_LEAN_AND_MEAN
#  endif
#  include <windows.h>
#else
#  define SECFW_IPC_UNIX 1
#  include <sys/socket.h>
#  include <sys/un.h>
#  include <sys/types.h>
#  include <sys/stat.h>
#  include <unistd.h>
#  include <cerrno>
#  include <cstring>
#  include <csignal>
#  include <fcntl.h>
#endif

namespace SecFW {

// ── Constants ─────────────────────────────────────────────────────────────────

// [N03] Hard cap. Reject BEFORE allocation — never alloc-then-check.
static constexpr std::size_t IPC_MAX_PAYLOAD_BYTES = 1u * 1024u * 1024u; // 1 MiB

// Frame header: 4-byte magic + 4-byte length = 8 bytes total
static constexpr uint8_t     IPC_MAGIC[4]    = { 0x53, 0x46, 0x57, 0x4D }; // "SFWM"
static constexpr std::size_t IPC_HEADER_SIZE = 8;

// AES-GCM envelope overhead: IV(12) + TAG(16) = 28 bytes
// CryptoEngine::encryptAESGCM output layout: [IV(12)] [TAG(16)] [CIPHERTEXT(N)]
static constexpr std::size_t IPC_GCM_IV_LEN   = 12;
static constexpr std::size_t IPC_GCM_TAG_LEN  = 16;
static constexpr std::size_t IPC_GCM_OVERHEAD = IPC_GCM_IV_LEN + IPC_GCM_TAG_LEN; // 28

// [BUG-IPC-04 FIX]: Minimum valid payload accounts for 4-byte body-len prefix
// in the plaintext. Was IPC_GCM_OVERHEAD (28). Now 28 + 4 = 32.
static constexpr std::size_t IPC_MIN_PAYLOAD_BYTES = IPC_GCM_OVERHEAD + 4; // 32

// [N06] Per-connection recv/send timeouts
static constexpr int IPC_RECV_TIMEOUT_SEC = 5;
static constexpr int IPC_SEND_TIMEOUT_SEC = 5;

static constexpr int IPC_LISTEN_BACKLOG = 16;

// HKDF domain for channel key — caller passes this to SecureKeyDerivation::derive()
static constexpr std::string_view IPC_HKDF_DOMAIN = "secfw-ipc-channel-v1";

// ── IpcPeerInfo ───────────────────────────────────────────────────────────────
// Verified peer credentials from SO_PEERCRED — [N04 FIX]

struct IpcPeerInfo {
    uid_t uid      { 0 };
    gid_t gid      { 0 };
    pid_t pid      { 0 };
    bool  verified { false };
};

// ── IpcMessage ────────────────────────────────────────────────────────────────
//
// Application-level message. Body is opaque bytes (JSON recommended).
//
// Serialised on-wire inside GCM ciphertext:
//   [4 bytes] body_len  — uint32_t little-endian
//   [n bytes] body      — UTF-8 string

struct IpcMessage {
    std::string body;

    static constexpr std::size_t MAX_BODY_BYTES =
        IPC_MAX_PAYLOAD_BYTES - IPC_GCM_OVERHEAD - 4;

    // [BUG-IPC-03 FIX]: Returns Result<SecBytes> so callers use .fail() cleanly.
    // Previously returned empty SecBytes{} on error — required fragile dual-check.
    [[nodiscard]] Result<SecBytes> serialise() const {
        if (body.size() > MAX_BODY_BYTES)
            return Result<SecBytes>::Failure(SecurityStatus::ERR_INPUT_INVALID,
                "IpcMessage::serialise: body " + std::to_string(body.size()) +
                " bytes > MAX_BODY_BYTES " + std::to_string(MAX_BODY_BYTES));

        auto bodyLen = static_cast<uint32_t>(body.size());
        SecBytes out;
        out.reserve(4 + body.size());
        out.push_back(static_cast<byte_t>( bodyLen        & 0xFF));
        out.push_back(static_cast<byte_t>((bodyLen >>  8) & 0xFF));
        out.push_back(static_cast<byte_t>((bodyLen >> 16) & 0xFF));
        out.push_back(static_cast<byte_t>((bodyLen >> 24) & 0xFF));
        for (char c : body) out.push_back(static_cast<byte_t>(c));
        return Result<SecBytes>::Success(std::move(out));
    }

    [[nodiscard]] static Result<IpcMessage> deserialise(const SecBytes& raw) {
        if (raw.size() < 4)
            return Result<IpcMessage>::Failure(SecurityStatus::ERR_INPUT_INVALID,
                "IpcMessage::deserialise: too short for body-length prefix");

        uint32_t bodyLen =
              static_cast<uint32_t>(raw[0])
            | static_cast<uint32_t>(raw[1]) <<  8
            | static_cast<uint32_t>(raw[2]) << 16
            | static_cast<uint32_t>(raw[3]) << 24;

        if (bodyLen > MAX_BODY_BYTES)
            return Result<IpcMessage>::Failure(SecurityStatus::ERR_INPUT_INVALID,
                "IpcMessage::deserialise: body_len " + std::to_string(bodyLen) +
                " > MAX_BODY_BYTES " + std::to_string(MAX_BODY_BYTES));

        if (raw.size() < 4 + static_cast<std::size_t>(bodyLen))
            return Result<IpcMessage>::Failure(SecurityStatus::ERR_INPUT_INVALID,
                "IpcMessage::deserialise: truncated body (have " +
                std::to_string(raw.size() - 4) +
                ", need " + std::to_string(bodyLen) + ")");

        IpcMessage msg;
        msg.body.assign(reinterpret_cast<const char*>(raw.data() + 4), bodyLen);
        return Result<IpcMessage>::Success(std::move(msg));
    }
};

// ── Internal platform helpers ─────────────────────────────────────────────────

namespace detail {

#ifdef SECFW_IPC_UNIX

using SocketFd = int;
static constexpr SocketFd INVALID_FD = -1;

// ── readFull — [N02 FIX] ─────────────────────────────────────────────────────
// Loops until all `len` bytes received. Short reads are normal on stream sockets.

[[nodiscard]] inline Result<void> readFull(SocketFd fd, void* buf, std::size_t len)
{
    byte_t*     ptr       = static_cast<byte_t*>(buf);
    std::size_t remaining = len;
    while (remaining > 0) {
        ssize_t n = ::recv(fd, ptr, remaining, MSG_WAITALL);
        if (n == 0)
            return Result<void>::Failure(SecurityStatus::ERR_CONN_CLOSED,
                "EOF after " + std::to_string(len - remaining) +
                "/" + std::to_string(len) + " bytes");
        if (n < 0) {
            int e = errno;
            if (e == EINTR)  continue; // [BUG-E06] signal-safe retry
            if (e == EAGAIN || e == EWOULDBLOCK)
                return Result<void>::Failure(SecurityStatus::ERR_TIMEOUT,
                    "recv timed out (SO_RCVTIMEO = " +
                    std::to_string(IPC_RECV_TIMEOUT_SEC) + "s)");
            return Result<void>::Failure(SecurityStatus::ERR_NETWORK_FAIL,
                std::string("recv: ") + ::strerror(e));
        }
        ptr       += static_cast<std::size_t>(n);
        remaining -= static_cast<std::size_t>(n);
    }
    return Result<void>::Success();
}

// ── writeFull — [N02 FIX, N05 FIX] ──────────────────────────────────────────
// Loops until all `len` bytes sent. MSG_NOSIGNAL prevents SIGPIPE.

[[nodiscard]] inline Result<void> writeFull(SocketFd fd,
                                             const void* buf, std::size_t len)
{
    const byte_t* ptr       = static_cast<const byte_t*>(buf);
    std::size_t   remaining = len;
    while (remaining > 0) {
        ssize_t n = ::send(fd, ptr, remaining, MSG_NOSIGNAL); // [N05 FIX]
        if (n < 0) {
            int e = errno;
            if (e == EINTR) continue;
            if (e == EPIPE || e == ECONNRESET)
                return Result<void>::Failure(SecurityStatus::ERR_CONN_CLOSED,
                    "peer closed during send (EPIPE/ECONNRESET)");
            if (e == EAGAIN || e == EWOULDBLOCK)
                return Result<void>::Failure(SecurityStatus::ERR_TIMEOUT,
                    "send timed out (SO_SNDTIMEO = " +
                    std::to_string(IPC_SEND_TIMEOUT_SEC) + "s)");
            return Result<void>::Failure(SecurityStatus::ERR_NETWORK_FAIL,
                std::string("send: ") + ::strerror(e));
        }
        ptr       += static_cast<std::size_t>(n);
        remaining -= static_cast<std::size_t>(n);
    }
    return Result<void>::Success();
}

// ── applyTimeouts — [N06 FIX] ────────────────────────────────────────────────
// Must be called on every accepted socket BEFORE reading any data.

[[nodiscard]] inline Result<void> applyTimeouts(SocketFd fd)
{
    struct timeval tv{ IPC_RECV_TIMEOUT_SEC, 0 };
    if (::setsockopt(fd, SOL_SOCKET, SO_RCVTIMEO, &tv, sizeof(tv)) != 0)
        return Result<void>::Failure(SecurityStatus::ERR_NETWORK_FAIL,
            std::string("SO_RCVTIMEO: ") + ::strerror(errno));
    tv.tv_sec = IPC_SEND_TIMEOUT_SEC;
    if (::setsockopt(fd, SOL_SOCKET, SO_SNDTIMEO, &tv, sizeof(tv)) != 0)
        return Result<void>::Failure(SecurityStatus::ERR_NETWORK_FAIL,
            std::string("SO_SNDTIMEO: ") + ::strerror(errno));
    return Result<void>::Success();
}

// ── verifyPeer — [N04 FIX] ───────────────────────────────────────────────────
// Reads SO_PEERCRED BEFORE any data is read. Returns peer UID/GID/PID.

[[nodiscard]] inline Result<IpcPeerInfo> verifyPeer(SocketFd fd)
{
    struct ucred cred{};
    socklen_t    len = sizeof(cred);
    if (::getsockopt(fd, SOL_SOCKET, SO_PEERCRED, &cred, &len) != 0)
        return Result<IpcPeerInfo>::Failure(SecurityStatus::ERR_PEER_REJECTED,
            std::string("SO_PEERCRED: ") + ::strerror(errno));
    return Result<IpcPeerInfo>::Success(
        IpcPeerInfo{ cred.uid, cred.gid, cred.pid, true });
}

// ── cleanupSocketFile — [N01 FIX, N07 FIX] ───────────────────────────────────
// Unconditional unlink. ENOENT is expected and silently ignored.
// Never call exists() before unlinking (TOCTOU).

inline void cleanupSocketFile(const std::string& path) noexcept {
    ::unlink(path.c_str());
}

// ── encryptMessage — [BUG-IPC-01 FIX] ───────────────────────────────────────
//
// v2.0 bug: generated ivRes and passed it as the `aad` (3rd) arg to
// encryptAESGCM. CryptoEngine generates its own IV internally — the 3rd
// param is AAD, not IV. decryptAESGCM had no aad → GCM tag failed always.
//
// Fix: call encryptAESGCM(plaintext, channelKey) with no aad.
// CryptoEngine output = [IV(12)] [TAG(16)] [CIPHERTEXT(N)].

[[nodiscard]] inline Result<SecBytes> encryptMessage(
    const SecBytes& plaintext, const SecBytes& channelKey)
{
    // No separate IV generation — CryptoEngine handles it.
    auto r = CryptoEngine::encryptAESGCM(plaintext, channelKey);
    if (r.fail())
        return Result<SecBytes>::Failure(r.status, "encryptMessage: " + r.message);
    return Result<SecBytes>::Success(std::move(r.value));
}

[[nodiscard]] inline Result<SecBytes> decryptMessage(
    const SecBytes& envelope, const SecBytes& channelKey)
{
    if (envelope.size() < IPC_GCM_OVERHEAD)
        return Result<SecBytes>::Failure(SecurityStatus::ERR_CRYPTO_FAIL,
            "decryptMessage: envelope " + std::to_string(envelope.size()) +
            " < GCM overhead " + std::to_string(IPC_GCM_OVERHEAD));
    // decryptAESGCM reads IV from [0..11], TAG from [12..27], decrypts [28..N]
    auto r = CryptoEngine::decryptAESGCM(envelope, channelKey);
    if (r.fail())
        return Result<SecBytes>::Failure(r.status, "decryptMessage: " + r.message);
    return Result<SecBytes>::Success(std::move(r.value));
}

#endif // SECFW_IPC_UNIX

} // namespace detail

// ── Public framing API ────────────────────────────────────────────────────────

#ifdef SECFW_IPC_UNIX

[[nodiscard]] inline Result<void> sendMessage(detail::SocketFd  fd,
                                               const IpcMessage& msg,
                                               const SecBytes&   channelKey)
{
    // [BUG-IPC-03 FIX]: serialise() returns Result<SecBytes>
    auto serRes = msg.serialise();
    if (serRes.fail())
        return Result<void>::Failure(serRes.status, serRes.message);

    auto encRes = detail::encryptMessage(serRes.value, channelKey);
    if (encRes.fail())
        return Result<void>::Failure(encRes.status, encRes.message);

    const SecBytes& payload = encRes.value;

    // [N03 FIX]: Validate size before uint32_t cast
    if (payload.size() > IPC_MAX_PAYLOAD_BYTES)
        return Result<void>::Failure(SecurityStatus::ERR_INPUT_INVALID,
            "sendMessage: payload " + std::to_string(payload.size()) +
            " > IPC_MAX_PAYLOAD_BYTES");

    auto payloadLen = static_cast<uint32_t>(payload.size());
    uint8_t header[IPC_HEADER_SIZE];
    std::memcpy(header, IPC_MAGIC, 4);
    header[4] = static_cast<uint8_t>( payloadLen        & 0xFF);
    header[5] = static_cast<uint8_t>((payloadLen >>  8) & 0xFF);
    header[6] = static_cast<uint8_t>((payloadLen >> 16) & 0xFF);
    header[7] = static_cast<uint8_t>((payloadLen >> 24) & 0xFF);

    auto r = detail::writeFull(fd, header, IPC_HEADER_SIZE); // [N02]
    if (r.fail()) return r;
    return detail::writeFull(fd, payload.data(), payload.size());
}

[[nodiscard]] inline Result<IpcMessage> recvMessage(detail::SocketFd fd,
                                                     const SecBytes&  channelKey)
{
    uint8_t header[IPC_HEADER_SIZE];
    {
        auto r = detail::readFull(fd, header, IPC_HEADER_SIZE); // [N02]
        if (r.fail()) return Result<IpcMessage>::Failure(r.status, r.message);
    }

    if (std::memcmp(header, IPC_MAGIC, 4) != 0)
        return Result<IpcMessage>::Failure(SecurityStatus::ERR_INPUT_INVALID,
            "recvMessage: bad frame magic — protocol mismatch or corruption");

    uint32_t payloadLen =
          static_cast<uint32_t>(header[4])
        | static_cast<uint32_t>(header[5]) <<  8
        | static_cast<uint32_t>(header[6]) << 16
        | static_cast<uint32_t>(header[7]) << 24;

    // [N03 FIX + BUG-IPC-04 FIX]: Validate BEFORE allocating.
    // Upper bound: cap at 1 MiB.
    // Lower bound: IPC_MIN_PAYLOAD_BYTES = 32 (GCM_OVERHEAD=28 + body_prefix=4).
    if (payloadLen > IPC_MAX_PAYLOAD_BYTES)
        return Result<IpcMessage>::Failure(SecurityStatus::ERR_INPUT_INVALID,
            "recvMessage: payload_len=" + std::to_string(payloadLen) +
            " > IPC_MAX_PAYLOAD_BYTES — possible DoS frame");

    if (payloadLen < IPC_MIN_PAYLOAD_BYTES)
        return Result<IpcMessage>::Failure(SecurityStatus::ERR_INPUT_INVALID,
            "recvMessage: payload_len=" + std::to_string(payloadLen) +
            " < IPC_MIN_PAYLOAD_BYTES=" + std::to_string(IPC_MIN_PAYLOAD_BYTES));

    SecBytes payload(payloadLen);
    {
        auto r = detail::readFull(fd, payload.data(), payloadLen); // [N02]
        if (r.fail()) return Result<IpcMessage>::Failure(r.status, r.message);
    }

    auto decRes = detail::decryptMessage(payload, channelKey);
    if (decRes.fail())
        return Result<IpcMessage>::Failure(decRes.status, decRes.message);

    return IpcMessage::deserialise(decRes.value);
}

// ══════════════════════════════════════════════════════════════════════════════
// UnixSocketServer
// ══════════════════════════════════════════════════════════════════════════════

class UnixSocketServer final {
public:
    using ConnectionHandler = std::function<void(
        detail::SocketFd   fd,
        const IpcPeerInfo& peer,
        const SecBytes&    channelKey,
        SecureLogger&      logger)>;

    // [BUG-IPC-02 FIX]: Returns unique_ptr — UnixSocketServer is not
    // default-constructible (owns listenFd_), so Result<UnixSocketServer>
    // won't compile. Callers: srvRes.value->run(handler)

    [[nodiscard]] static Result<std::unique_ptr<UnixSocketServer>> create(
        const std::string& socketPath,
        SecBytes           channelKey,
        SecureLogger&      logger,
        uid_t              allowedUid = static_cast<uid_t>(-1))
    {
        // [BUG-E04]: isValidSocketPath() enforces UNIX_PATH_MAX (108 bytes)
        auto pathCheck = InputValidator::isValidSocketPath(socketPath);
        if (pathCheck.fail())
            return Result<std::unique_ptr<UnixSocketServer>>::Failure(
                pathCheck.status, "UnixSocketServer::create: " + pathCheck.message);

        ::signal(SIGPIPE, SIG_IGN);                      // [N05 FIX]
        detail::cleanupSocketFile(socketPath);            // [N01 FIX]: no TOCTOU

        int fd = ::socket(AF_UNIX, SOCK_STREAM, 0);
        if (fd < 0)
            return Result<std::unique_ptr<UnixSocketServer>>::Failure(
                SecurityStatus::ERR_NETWORK_FAIL,
                std::string("socket: ") + ::strerror(errno));

        struct sockaddr_un addr{};
        addr.sun_family = AF_UNIX;
        std::strncpy(addr.sun_path, socketPath.c_str(), sizeof(addr.sun_path) - 1);

        if (::bind(fd, reinterpret_cast<sockaddr*>(&addr), sizeof(addr)) != 0) {
            int e = errno; ::close(fd);
            return Result<std::unique_ptr<UnixSocketServer>>::Failure(
                SecurityStatus::ERR_NETWORK_FAIL, std::string("bind: ") + ::strerror(e));
        }

        // Restrict socket file to owner (mode 0600) — first layer of defence
        if (::chmod(socketPath.c_str(), 0600) != 0) {
            int e = errno; ::close(fd); detail::cleanupSocketFile(socketPath);
            return Result<std::unique_ptr<UnixSocketServer>>::Failure(
                SecurityStatus::ERR_NETWORK_FAIL,
                std::string("chmod(0600) socket: ") + ::strerror(e));
        }

        if (::listen(fd, IPC_LISTEN_BACKLOG) != 0) {
            int e = errno; ::close(fd); detail::cleanupSocketFile(socketPath);
            return Result<std::unique_ptr<UnixSocketServer>>::Failure(
                SecurityStatus::ERR_NETWORK_FAIL,
                std::string("listen: ") + ::strerror(e));
        }

        uid_t effectiveUid = (allowedUid == static_cast<uid_t>(-1))
            ? ::getuid() : allowedUid;

        // Local helper subclass so make_unique can reach protected ctor
        struct Priv : UnixSocketServer {
            Priv(int f, std::string p, SecBytes k, SecureLogger& l, uid_t u)
                : UnixSocketServer(f, std::move(p), std::move(k), l, u) {}
        };
        auto ptr = std::make_unique<Priv>(
            fd, socketPath, std::move(channelKey), logger, effectiveUid);

        return Result<std::unique_ptr<UnixSocketServer>>::Success(std::move(ptr));
    }

    // ── run — blocking accept loop ────────────────────────────────────────────
    // [N04 FIX]: SO_PEERCRED verified on every socket before data
    // [N06 FIX]: Timeouts applied immediately after accept()
    // [BUG-E06]: EINTR retry

    void run(ConnectionHandler handler) {
        running_.store(true, std::memory_order_relaxed);
        logger_.info("UnixSocketServer: listening on " + socketPath_);

        while (running_.load(std::memory_order_relaxed)) {
            int clientFd = ::accept(listenFd_, nullptr, nullptr);

            if (clientFd < 0) {
                int e = errno;
                if (e == EINTR) continue;                // [BUG-E06]: not an error
                if (!running_.load(std::memory_order_relaxed)) break;
                logger_.error("accept: " + std::string(::strerror(e)));
                continue;
            }

            // [N06]: timeouts before reading anything
            auto toRes = detail::applyTimeouts(clientFd);
            if (toRes.fail()) {
                logger_.warn("applyTimeouts: " + toRes.message);
                ::close(clientFd); continue;
            }

            // [N04]: peer credentials before data
            auto peerRes = detail::verifyPeer(clientFd);
            if (peerRes.fail()) {
                logger_.warn("SO_PEERCRED: " + peerRes.message);
                ::close(clientFd); continue;
            }

            const IpcPeerInfo& peer = peerRes.value;
            if (peer.uid != allowedUid_) {
                logger_.warn("rejected UID=" + std::to_string(peer.uid) +
                             " PID=" + std::to_string(peer.pid) +
                             " (allowed=" + std::to_string(allowedUid_) + ")");
                ::close(clientFd); continue;
            }

            logger_.info("accepted PID=" + std::to_string(peer.pid) +
                         " UID=" + std::to_string(peer.uid));

            try { handler(clientFd, peer, channelKey_, logger_); }
            catch (const std::exception& e) {
                logger_.error("handler exception: " + std::string(e.what()));
            } catch (...) {
                logger_.error("handler threw unknown exception");
            }

            ::close(clientFd);
        }

        logger_.info("UnixSocketServer: accept loop exited");
    }

    void stop() noexcept {
        running_.store(false, std::memory_order_relaxed);
        if (listenFd_ >= 0) ::shutdown(listenFd_, SHUT_RDWR);
    }

    // [N07 FIX]: RAII — socket file removed on destructor
    ~UnixSocketServer() noexcept {
        stop();
        if (listenFd_ >= 0) { ::close(listenFd_); listenFd_ = -1; }
        if (!socketPath_.empty()) detail::cleanupSocketFile(socketPath_);
    }

    UnixSocketServer(const UnixSocketServer&)            = delete;
    UnixSocketServer& operator=(const UnixSocketServer&) = delete;
    UnixSocketServer(UnixSocketServer&&)                 = delete;
    UnixSocketServer& operator=(UnixSocketServer&&)      = delete;

protected:
    UnixSocketServer(int fd, std::string path,
                     SecBytes key, SecureLogger& log, uid_t uid)
        : listenFd_(fd), socketPath_(std::move(path))
        , channelKey_(std::move(key)), logger_(log)
        , allowedUid_(uid), running_(false) {}

private:
    int               listenFd_   { -1 };
    std::string       socketPath_ {};
    SecBytes          channelKey_ {};
    SecureLogger&     logger_;
    uid_t             allowedUid_ { 0 };
    std::atomic<bool> running_    { false };
};

// ══════════════════════════════════════════════════════════════════════════════
// UnixSocketClient
// ══════════════════════════════════════════════════════════════════════════════

class UnixSocketClient final {
public:
    // [BUG-IPC-02 FIX]: Returns unique_ptr. Callers: cliRes.value->send(msg)

    [[nodiscard]] static Result<std::unique_ptr<UnixSocketClient>> connect(
        const std::string& socketPath,
        SecBytes           channelKey)
    {
        auto pathCheck = InputValidator::isValidSocketPath(socketPath);
        if (pathCheck.fail())
            return Result<std::unique_ptr<UnixSocketClient>>::Failure(
                pathCheck.status,
                "UnixSocketClient::connect: " + pathCheck.message);

        ::signal(SIGPIPE, SIG_IGN); // [N05]

        int fd = ::socket(AF_UNIX, SOCK_STREAM, 0);
        if (fd < 0)
            return Result<std::unique_ptr<UnixSocketClient>>::Failure(
                SecurityStatus::ERR_NETWORK_FAIL,
                std::string("socket: ") + ::strerror(errno));

        struct sockaddr_un addr{};
        addr.sun_family = AF_UNIX;
        std::strncpy(addr.sun_path, socketPath.c_str(), sizeof(addr.sun_path) - 1);

        if (::connect(fd, reinterpret_cast<sockaddr*>(&addr), sizeof(addr)) != 0) {
            int e = errno; ::close(fd);
            return Result<std::unique_ptr<UnixSocketClient>>::Failure(
                SecurityStatus::ERR_NETWORK_FAIL,
                std::string("connect: ") + ::strerror(e));
        }

        // [N06]: timeouts immediately after connect
        struct timeval tv{ IPC_RECV_TIMEOUT_SEC, 0 };
        ::setsockopt(fd, SOL_SOCKET, SO_RCVTIMEO, &tv, sizeof(tv));
        tv.tv_sec = IPC_SEND_TIMEOUT_SEC;
        ::setsockopt(fd, SOL_SOCKET, SO_SNDTIMEO, &tv, sizeof(tv));

        struct Priv : UnixSocketClient {
            Priv(int f, SecBytes k) : UnixSocketClient(f, std::move(k)) {}
        };
        return Result<std::unique_ptr<UnixSocketClient>>::Success(
            std::make_unique<Priv>(fd, std::move(channelKey)));
    }

    [[nodiscard]] Result<void>       send(const IpcMessage& msg) {
        return sendMessage(fd_, msg, channelKey_);
    }
    [[nodiscard]] Result<IpcMessage> recv() {
        return recvMessage(fd_, channelKey_);
    }

    ~UnixSocketClient() noexcept {
        if (fd_ >= 0) { ::close(fd_); fd_ = -1; }
    }

    UnixSocketClient(const UnixSocketClient&)            = delete;
    UnixSocketClient& operator=(const UnixSocketClient&) = delete;
    UnixSocketClient(UnixSocketClient&&)                 = delete;
    UnixSocketClient& operator=(UnixSocketClient&&)      = delete;

protected:
    UnixSocketClient(int fd, SecBytes key)
        : fd_(fd), channelKey_(std::move(key)) {}

private:
    int      fd_         { -1 };
    SecBytes channelKey_ {};
};

#else // SECFW_IPC_WINDOWS
// ══════════════════════════════════════════════════════════════════════════════
// Windows Named Pipe stub — [N08: platform abstraction]
// Identical API surface; replace body with Named Pipe implementation.
// ══════════════════════════════════════════════════════════════════════════════

class UnixSocketServer final {
public:
    using ConnectionHandler = std::function<void(HANDLE, const IpcPeerInfo&,
                                                 const SecBytes&, SecureLogger&)>;
    [[nodiscard]] static Result<std::unique_ptr<UnixSocketServer>> create(
        const std::string&, SecBytes, SecureLogger&, DWORD = 0)
    {
        return Result<std::unique_ptr<UnixSocketServer>>::Failure(
            SecurityStatus::ERR_INTERNAL,
            "UnixSocketServer: Windows Named Pipe not implemented in v2.0.");
    }
    void run(ConnectionHandler) {}
    void stop() noexcept {}
    ~UnixSocketServer() noexcept = default;
    UnixSocketServer(const UnixSocketServer&) = delete;
    UnixSocketServer& operator=(const UnixSocketServer&) = delete;
protected:
    UnixSocketServer() = default;
};

class UnixSocketClient final {
public:
    [[nodiscard]] static Result<std::unique_ptr<UnixSocketClient>> connect(
        const std::string&, SecBytes)
    {
        return Result<std::unique_ptr<UnixSocketClient>>::Failure(
            SecurityStatus::ERR_INTERNAL,
            "UnixSocketClient: Windows Named Pipe not implemented in v2.0.");
    }
    [[nodiscard]] Result<void>       send(const IpcMessage&) {
        return Result<void>::Failure(SecurityStatus::ERR_INTERNAL, "not implemented");
    }
    [[nodiscard]] Result<IpcMessage> recv() {
        return Result<IpcMessage>::Failure(SecurityStatus::ERR_INTERNAL, "not implemented");
    }
    ~UnixSocketClient() noexcept = default;
    UnixSocketClient(const UnixSocketClient&) = delete;
    UnixSocketClient& operator=(const UnixSocketClient&) = delete;
protected:
    UnixSocketClient() = default;
};

#endif // SECFW_IPC_WINDOWS

} // namespace SecFW
